import PDFDocument from 'pdfkit';

export const generateChallanPDF = (challan: any): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 40, size: 'A4' });
      const buffers: Buffer[] = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });

      // Header
      doc
        .fillColor('#1E293B')
        .fontSize(22)
        .text('MINI ERP DISTRIBUTION PORTAL', { align: 'center' });
      doc
        .fontSize(10)
        .fillColor('#64748B')
        .text('Official Sales Challan / Delivery Order', { align: 'center' })
        .moveDown(1.5);

      // Divider
      doc
        .strokeColor('#CBD5E1')
        .lineWidth(1)
        .moveTo(40, doc.y)
        .lineTo(555, doc.y)
        .stroke()
        .moveDown(1);

      // Challan Meta
      const startY = doc.y;
      doc.fontSize(11).fillColor('#0F172A');
      doc.text(`Challan No: ${challan.challanNumber}`, 40, startY);
      doc.text(`Date: ${new Date(challan.createdAt).toLocaleDateString()}`, 40, startY + 16);
      doc.text(`Status: ${challan.status}`, 40, startY + 32);

      // Customer Info
      doc.text(`Customer Name: ${challan.customer.customerName}`, 300, startY);
      doc.text(`Business Name: ${challan.customer.businessName}`, 300, startY + 16);
      doc.text(`GST No: ${challan.customer.gstNumber || 'N/A'}`, 300, startY + 32);
      doc.moveDown(3);

      // Table Header
      const tableTop = startY + 65;
      doc.fillColor('#475569').fontSize(10).font('Helvetica-Bold');
      doc.text('Item Description', 40, tableTop);
      doc.text('SKU', 250, tableTop);
      doc.text('Qty', 350, tableTop, { width: 50, align: 'right' });
      doc.text('Unit Price', 410, tableTop, { width: 60, align: 'right' });
      doc.text('Total', 480, tableTop, { width: 75, align: 'right' });

      doc
        .strokeColor('#94A3B8')
        .lineWidth(0.5)
        .moveTo(40, tableTop + 14)
        .lineTo(555, tableTop + 14)
        .stroke();

      // Items
      let itemY = tableTop + 22;
      doc.font('Helvetica').fontSize(9).fillColor('#1E293B');

      if (challan.items && Array.isArray(challan.items)) {
        challan.items.forEach((item: any) => {
          const snapshot = typeof item.productSnapshot === 'string' 
            ? JSON.parse(item.productSnapshot) 
            : item.productSnapshot;
          const name = snapshot?.name || 'Product';
          const sku = snapshot?.sku || '-';
          const qty = item.quantity;
          const price = Number(item.priceSnapshot).toFixed(2);
          const lineTotal = (qty * Number(item.priceSnapshot)).toFixed(2);

          doc.text(name, 40, itemY, { width: 200 });
          doc.text(sku, 250, itemY);
          doc.text(qty.toString(), 350, itemY, { width: 50, align: 'right' });
          doc.text(`$${price}`, 410, itemY, { width: 60, align: 'right' });
          doc.text(`$${lineTotal}`, 480, itemY, { width: 75, align: 'right' });

          itemY += 20;
        });
      }

      // Summary
      doc
        .strokeColor('#CBD5E1')
        .lineWidth(1)
        .moveTo(40, itemY + 5)
        .lineTo(555, itemY + 5)
        .stroke();

      const summaryY = itemY + 15;
      doc.font('Helvetica-Bold').fontSize(11).fillColor('#0F172A');
      doc.text(`Total Quantity: ${challan.totalQuantity}`, 40, summaryY);
      doc.text(`Total Amount: $${Number(challan.totalAmount).toFixed(2)}`, 380, summaryY, { width: 175, align: 'right' });

      // Footer
      doc
        .fontSize(9)
        .fillColor('#94A3B8')
        .text('Thank you for your business! Generated by Mini ERP Operations Portal.', 40, 780, {
          align: 'center',
          width: 515,
        });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};
